const ProductsActionTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  // POST_TASK_START: "POST_TASK_START",
  // POST_TASK_SUCESS: "POST_TASK_SUCESS",
  // POST_TASK_FAILURE: "POST_TASK_FAILURE",
  // DELETE_TASK_START: "DELETE_TASK_START",
  // DELETE_TASK_SUCESS: "DELETE_TASK_SUCESS",
  // DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  // UPDATE_TASK_START: "UPDATE_TASK_START",
  // UPDATE_TASK_SUCESS: "UPDATE_TASK_SUCESS",
  // UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
};

export default ProductsActionTypes;
