const CustomersActionTypes = {
  FETCH_CUSTOMERS_START: "FETCH_CUSTOMERS_START",
  FETCH_CUSTOMERS_SUCESS: "FETCH_CUSTOMERS_SUCESS",
  FETCH_CUSTOMERS_FAILURE: "FETCH_CUSTOMERS_FAILURE",
  POST_CUSTOMER_START: "POST_CUSTOMER_START",
  POST_CUSTOMER_SUCCESS: "POST_CUSTOMER_SUCCESS",
  POST_CUSTOMER_FAILURE: "POST_CUSTOMER_FAILURE",
  GET_AVATAR_START: "GET_AVATAR_START",
  GET_AVATAR_SUCCESS: "GET_AVATAR_SUCCESS",
  GET_AVATAR_FAILURE: "GET_AVATAR_FAILURE",
  // DELETE_TASK_START: "DELETE_TASK_START",
  // DELETE_TASK_SUCESS: "DELETE_TASK_SUCESS",
  // DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  // UPDATE_TASK_START: "UPDATE_TASK_START",
  // UPDATE_TASK_SUCESS: "UPDATE_TASK_SUCESS",
  // UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
};

export default CustomersActionTypes;
