const OrdersActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCESS: "FETCH_ORDERS_SUCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  // POST_TASK_START: "POST_TASK_START",
  // POST_TASK_SUCESS: "POST_TASK_SUCESS",
  // POST_TASK_FAILURE: "POST_TASK_FAILURE",
  // DELETE_TASK_START: "DELETE_TASK_START",
  // DELETE_TASK_SUCESS: "DELETE_TASK_SUCESS",
  // DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  // UPDATE_TASK_START: "UPDATE_TASK_START",
  // UPDATE_TASK_SUCESS: "UPDATE_TASK_SUCESS",
  // UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
};

export default OrdersActionTypes;
